export const countryFlags: Record<string, string> = {
  // 🇵🇹 Português (seed local)
  Brasil: "br",
  Sérvia: "rs",
  Argentina: "ar",
  Nigéria: "ng",
  Alemanha: "de",
  México: "mx",
  França: "fr",
  Tunísia: "tn",
  Gana: "gh",
  Espanha: "es",
  Inglaterra: "gb-eng",
  Irã: "ir",
  Holanda: "nl",
  Uruguai: "uy",
  Paraguai: "py",
  Colômbia: "co",
  Equador: "ec",
  Bolívia: "bo",
  Itália: "it",
  Croácia: "hr",
  Dinamarca: "dk",
  Suíça: "ch",
  Suécia: "se",
  Polônia: "pl",
  Ucrânia: "ua",
  Áustria: "at",
  Hungria: "hu",
  Grécia: "gr",
  Turquia: "tr",
  "República Tcheca": "cz",
  Eslováquia: "sk",
  Romênia: "ro",
  Rússia: "ru",
  Noruega: "no",
  Escócia: "gb-sct",
  "País de Gales": "gb-wls",
  Irlanda: "ie",
  "Irlanda do Norte": "gb-nir",
  Canadá: "ca",
  Panamá: "pa",
  Japão: "jp",
  "Coreia do Sul": "kr",
  Austrália: "au",
  "Arábia Saudita": "sa",
  "África do Sul": "za",
  Camarões: "cm",
  Marrocos: "ma",
  Argélia: "dz",
  Egito: "eg",
  "Costa do Marfim": "ci",
  "Nova Zelândia": "nz",

  // 🇬🇧 English (Football-Data.org API)
  Brazil: "br",
  Serbia: "rs",
  Nigeria: "ng",
  Germany: "de",
  Mexico: "mx",
  France: "fr",
  Tunisia: "tn",
  Portugal: "pt",
  Ghana: "gh",
  Spain: "es",
  "Costa Rica": "cr",
  England: "gb-eng",
  Iran: "ir",
  Netherlands: "nl",
  Senegal: "sn",
  Uruguay: "uy",
  Paraguay: "py",
  Chile: "cl",
  Colombia: "co",
  Ecuador: "ec",
  Peru: "pe",
  Venezuela: "ve",
  Bolivia: "bo",
  Italy: "it",
  Croatia: "hr",
  Denmark: "dk",
  Switzerland: "ch",
  Sweden: "se",
  Poland: "pl",
  Ukraine: "ua",
  Austria: "at",
  Hungary: "hu",
  Greece: "gr",
  Turkey: "tr",
  "Czech Republic": "cz",
  Slovakia: "sk",
  Romania: "ro",
  Russia: "ru",
  Norway: "no",
  Scotland: "gb-sct",
  Wales: "gb-wls",
  Ireland: "ie",
  "Northern Ireland": "gb-nir",
  Canada: "ca",
  Jamaica: "jm",
  Honduras: "hn",
  "El Salvador": "sv",
  Panama: "pa",
  Japan: "jp",
  "South Korea": "kr",
  Australia: "au",
  "Saudi Arabia": "sa",
  "South Africa": "za",
  Cameroon: "cm",
  Morocco: "ma",
  Algeria: "dz",
  Egypt: "eg",
  "Ivory Coast": "ci",
  "New Zealand": "nz",

  // 🏆 Football-Data.org aliases específicos
  USA: "us",
  "United States": "us",
  "Korea Republic": "kr",
  "IR Iran": "ir",
  "Côte d'Ivoire": "ci",
  "DR Congo": "cd",
  "Congo DR": "cd",
  Uzbekistan: "uz",
  Czechia: "cz",
  Belgium: "be",
  Bélgica: "be",
  "Bosnia-Herzegovina": "ba",
  "Cape Verde Islands": "cv",
  Curaçao: "cw",
  "Republic of Ireland": "ie",
  "Korea DPR": "kp",
  "North Korea": "kp",
  Syria: "sy",
  Lebanon: "lb",
  Palestine: "ps",
  Jordan: "jo",
  Iraq: "iq",
  Yemen: "ye",
  Oman: "om",
  Bahrain: "bh",
  Qatar: "qa",
  Kuwait: "kw",
  UAE: "ae",
  "United Arab Emirates": "ae",
  Thailand: "th",
  Vietnam: "vn",
  Indonesia: "id",
  Malaysia: "my",
  Philippines: "ph",
  Singapore: "sg",
  China: "cn",
  "Chinese Taipei": "tw",
  India: "in",
  Pakistan: "pk",
  Bangladesh: "bd",
  "Sri Lanka": "lk",
  Nepal: "np",
  "Bosnia and Herzegovina": "ba",
  "North Macedonia": "mk",
  Albania: "al",
  Montenegro: "me",
  Kosovo: "xk",
  Belarus: "by",
  Lithuania: "lt",
  Latvia: "lv",
  Estonia: "ee",
  Slovenia: "si",
  "Faroe Islands": "fo",
  Malta: "mt",
  Luxembourg: "lu",
  Andorra: "ad",
  Cyprus: "cy",
  Georgia: "ge",
  Armenia: "am",
  Azerbaijan: "az",
  Kazakhstan: "kz",
  Israel: "il",
  "Burkina Faso": "bf",
  Mali: "ml",
  Zambia: "zm",
  "Cape Verde": "cv",
  Madagascar: "mg",
  Comoros: "km",
  Mauritius: "mu",
  Togo: "tg",
  Benin: "bj",
  Congo: "cg",
  Angola: "ao",
  Sudan: "sd",
  Ethiopia: "et",
  Kenya: "ke",
  Uganda: "ug",
  Tanzania: "tz",
  Mozambique: "mz",
  Zimbabwe: "zw",
  Namibia: "na",
  Botswana: "bw",
  Lesotho: "ls",
  Swaziland: "sz",
  Eswatini: "sz",
  Liberia: "lr",
  "Sierra Leone": "sl",
  "Guinea Bissau": "gw",
  Gambia: "gm",
  Guinea: "gn",
  "Equatorial Guinea": "gq",
  Gabon: "ga",
  "Central African Republic": "cf",
  Chad: "td",
  Niger: "ne",
  Mauritania: "mr",
  Burundi: "bi",
  Rwanda: "rw",
  Somalia: "so",
  Djibouti: "dj",
  "South Sudan": "ss",
  Eritrea: "er",
  Malawi: "mw",
  Seychelles: "sc",
  Bahamas: "bs",
  Barbados: "bb",
  Cuba: "cu",
  "Dominican Republic": "do",
  Haiti: "ht",
  "Trinidad and Tobago": "tt",
  Guatemala: "gt",
  Belize: "bz",
  Nicaragua: "ni",
  Fiji: "fj",
  "Papua New Guinea": "pg",
  "Solomon Islands": "sb",
  Tahiti: "pf",
  "New Caledonia": "nc",
  Vanuatu: "vu",
  Samoa: "ws",
  "American Samoa": "as",
  Tonga: "to",
  "Cook Islands": "ck",
  "French Polynesia": "pf",
}

const cache = new Map<string, string>()
const normalizedMap = new Map<string, string>()

for (const [k, v] of Object.entries(countryFlags)) {
  const nk = k.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")
  normalizedMap.set(nk, v)
  cache.set(k, v)
}

export function resolveCountryCode(country: string): string {
  if (!country) return "unknown"

  const cached = cache.get(country)
  if (cached) return cached

  const key = country.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")
  return normalizedMap.get(key) ?? "unknown"
}
